会場を株式会社インプレスに変更した
tezshi/ichiyasaGitSample pull request #1
Opened 2023-03-14 09:29 UTC by tezshi

### 変更内容
イベント開催会場を『株式会社インプレス』に変更しました。

### 背景
『株式会社インプレス』さんがイベント会場を提供してくださることになりました。

2023-03-14 09:49 UTC, TestMarushima commented
会場が決定して一安心ですね。

2023-03-14 23:25 UTC, TestMarushima commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社と社名の間に半角 Space を入れてください。

2023-03-14 23:28 UTC, TestMarushima requested changes

2023-03-14 23:28 UTC, TestMarushima commented on index.html
>                          <p>3月23日 19:00開始</p>
開始の前に半角 Space を入れてください。

2023-03-14 23:33 UTC, TestMarushima requested changes
2点の修正をお願いします。

2023-03-14 23:33 UTC, TestMarushima commented on index.html
>                          <p>3月23日 19:00開始</p>
開始の前に半角 Space を入れてください。

2023-03-14 23:33 UTC, TestMarushima commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
社名の前に半角 Space を入れてください。

2023-03-14 23:46 UTC, tezshi reviewed
半角 Space 挿入が完了しました。

2023-03-14 23:48 UTC, TestMarushima approved these changes
確認しました。
修正ありがとうございました。

2023-03-14 23:53 UTC, TestMarushima requested changes
HTML についての確認です。

2023-03-14 23:53 UTC, TestMarushima commented on index.html
> -                        <p>3月23日 19:00開始</p>
list 分を使うべきでは？

2023-03-14 23:55 UTC, tezshi commented on index.html
> -                        <p>3月23日 19:00開始</p>
確かにそちらの方が見栄えがしますね。
修正に3日ほどかかります。
少々お待ちください。

2023-03-15 00:04 UTC, TestMarushima commented
3日もかかるのであれば、今のままで結構です。
お騒がせしました。

2023-03-15 00:07 UTC, TestMarushima approved these changes

2023-03-15 04:36 UTC, merged